cos:
    secretId: AKIDpPkpyqLpxpQN4ohXYJo32lQpysVId53s
    secretKey: gJZddMlumwpSn57sMZcOuSjmY2GrKN6Z
    localhost: https://20200715-1301193990.cos.ap-shanghai.myqcloud.com
    region: ap-shanghai
    bucketName: 20200715-1301193990
spring:
    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB
